config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :workoutmenus do
    collection do
      get 'confirm'
    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :useradvices, only: [:new, :create, :show]
  resources :advicediaries, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'confirm'
    end
    collection do
      get 'choice'
    end
    collection do
      get 'content'
    end
  end
  resources :fooddiaries do
    collection do
      get 'confirm'
    end
    # get :autocomplete_fooddate_foodname, :on => :collection
  end
  resources :idealweights
  resources :advicemenus do
    collection do
      get 'introduction'
    end
  end
  resources :weightchanges
end

app/models/advicediary.rb
class Advicediary < ApplicationRecord
  
  def self.search(search) 
    if search
      Advicediary.where(['created_at LIKE ?', "%#{search}%"])
    else
      Advicediary.where(created_at: Date.current.all_day)
    end
  end
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :advicemenu
  belongs_to :useradvice
  validates :useradvice_id, presence: true
  
  belongs_to :idealweight
  
end

app/models/advicemenu.rb
class Advicemenu < ApplicationRecord
  has_many :advicediaries
  
  def self.search(search) 
    if search
      Advicemenu.where(['menu LIKE ?', "%#{search}%"])
    else
      Advicemenu.all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fooddate.rb
class Fooddate < ApplicationRecord
  has_many :fooddiaries
end

app/models/fooddiary.rb
class Fooddiary < ApplicationRecord
  
  # validates :gram, :kcal, :protein, :fat, :carbo, :timing, :fooddate_id, presence: true

  belongs_to :fooddate
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :idealweight
  
  def self.search(search) 
    if search
      Fooddiary.where(['created_at LIKE ?', "%#{search}%"]) 
    else
      Fooddiary.where(created_at: Date.current.all_day)
    end
  end

  before_save do
    self.kcal = (gram)*(fooddate.kcal)
    self.protein = (gram)*(fooddate.protein)
    self.fat = (gram)*(fooddate.fat)
    self.carbo = (gram)*(fooddate.carbo)
  end
  
  
end

app/models/idealweight.rb
class Idealweight < ApplicationRecord
  
  belongs_to :user
  has_many :fooddiaries
  has_many :advicediaries
  has_many :weightchanges
  
  before_save do
    if user.sex == "男"
      self.basemetabolism = 13.397*(weight)+4.799*(height)-5.677*(user.age)+88.362 #男性の場合
    else
      self.basemetabolism = 9.247*(weight)+3.098*(height)-4.33*(user.age)+447.593 #女性の場合
    end
    self.kcalburned = (basemetabolism)*(exerciselevel)
    self.minusweight = (weight)-(targetweight)
    self.minuskcal = (minusweight)*7000
    self.kcalintake = (kcalburned)-(minuskcal)/(period)
    self.intakeproteingram = (weight)*2
    self.intakeproteinkcal = (weight)*2*4
    self.intakefatgram = (weight)*0.7
    self.intakefatkcal = (weight)*0.7*9
    self.intakecarbokcal = (kcalintake)-(intakeproteinkcal)-(intakefatkcal)
    self.intakecarbogram = (intakecarbokcal)/4
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_one_attached :image
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :workoutmenus
  has_many :workoutdates
  has_many :fooddiaries
  has_one :useradvice
  has_many :advicediaries
  
  has_one :idealweight
  # accepts_nested_attributes_for :idealweight
  
  has_many :weightchanges
  
  def self.search(search) #index画面
    if search
      where(['created_at LIKE ?', "%#{search}%"]) 
    end
  end
  
  def set_date
    birthday.try(:strftime, "%Y%m%d").to_i
  end
  
  def today_date
    @today = Date.today
    @today.strftime("%Y%m%d").to_i
  end
  
  before_save do
    self.age = (today_date-set_date)/10000
  end
  
end

app/models/useradvice.rb
class Useradvice < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  
  has_many :advicediaries
end

app/models/weightchange.rb
class Weightchange < ApplicationRecord
  belongs_to :user
  belongs_to :idealweight
end

app/models/workoutdate.rb
class Workoutdate < ApplicationRecord
  has_many :workoutdiaries
  belongs_to :user
end

app/models/workoutmenu.rb
class Workoutmenu < ApplicationRecord
  
  validates :settype, :weight, :reps, presence: true
  
  def self.search(search) 
    if search
      Workoutmenu.where(['created_at LIKE ?', "%#{search}%"])
    else
      Workoutmenu.where(created_at: Date.current.all_day)
    end
  end
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :workoutdate
  
end

app/controllers/advicemenus_controller.rb
class AdvicemenusController < ApplicationController
  def introduction
    @advicemenus = Advicemenu.search(params[:search])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    # @workoutmenus = Workoutmenu.all
    @workoutmenus = params[:search].present? ? current_user.workoutmenus.where('created_at LIKE(?)', "%#{params[:search]}%"): []
  end
  
  def show
    @user = User.find(params[:id])
    @username = current_user.username
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end
  
  private
  def user_params
    params.require(:user).permit(:image, :username, :text, :sex, :area, :birthday, :age,
    idealweight_attributes: [:id, :height, :weight, :targetweight, :exerciselevel, :period, :basemetabolism, :kcalburned, :minusweight, :minuskcal, :kcalintake, :intakeproteingram, :intakeproteinkcal, :intakefatgram, :intakefatkcal, :intakecarbogram, :intakecarbokcal, :user_id])
  end
end

app/controllers/workoutmenus_controller.rb
class WorkoutmenusController < ApplicationController
  # autocomplete :workoutmenu, :menu, full: true
  before_action :authenticate_user!
  
  def confirm
  end
  
  def index
    @workoutmenus = current_user.workoutmenus.search(params[:search])
  end
  
  def new
    @workoutmenu = current_user.workoutmenus.new
  end
  
  def create
    @workoutmenus = current_user.workoutmenus.create(workoutmenu_params)
    redirect_to action: 'index'
  end
  
  def destroy
    current_user.workoutmenus.find(params[:id]).destroy
    @workoutmenus = current_user.workoutmenus.all
    redirect_to action: 'index'
  end
  
  def edit
    @workoutmenu = current_user.workoutmenus.find(params[:id])
  end
  
  def update
    @workoutmenu = current_user.workoutmenus.find(params[:id])
    @workoutmenu.update(workoutmenu_params)
    redirect_to action: 'index'
  end
  
  private
  def workoutmenu_params
    params.require(:workoutmenu).permit(:settype, :weight, :reps, :menu, :user_id, :workoutdate_id, :created_at)
  end
end

app/helpers/advicediaries_helper.rb
module AdvicediariesHelper
end

app/helpers/advicemenus_helper.rb
module AdvicemenusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fooddiaries_helper.rb
module FooddiariesHelper
end

app/helpers/idealweights_helper.rb
module IdealweightsHelper
end

app/helpers/useradvices_helper.rb
module UseradvicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weightchanges_helper.rb
module WeightchangesHelper
end

app/helpers/workoutmenus_helper.rb
module WorkoutmenusHelper
end

app/views/workoutmenus/_workoutmenu.html.erb
<tbody>
  <tr>
    <td><%= workoutmenu.workoutdate.menu %></td>
    <td><%= workoutmenu.settype %></td>
    <td><%= workoutmenu.weight %>kg</td>
    <td><%= workoutmenu.reps %>reps</td>
    <td>
      <div class="dropdown">
        <button class="btn bmd-btn-icon dropdown-toggle" type="button" id="ex1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="material-icons">more_vert</i>
        </button>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="ex1">
          <%= link_to "編集", "/workoutmenus/#{workoutmenu.id}/edit", class: "dropdown-item" %>
          <%= link_to '削除', workoutmenu_path(workoutmenu), method: :delete, remote: true, class: "dropdown-item" %>
        </div>
      </div>
    </td>
  </tr>
</tbody>

app/views/workoutmenus/confirm.html.erb
<div class="container-fuild">
  <h2>Training Diary</h2>
  <hr>
  <div class="row">
    <div class="form-group col-md-12">
      <p>Life changes if your body changes. You have the potential.</p>
      <p> Let's start!</p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
      <img class="card-img-top" src="https://moneytimes.jp/files/topics/2827_ext_01_0.jpg" alt="Card image cap" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">本日のトレーニングを記録する</h5>
          <p class="card-text">born to LIFT</p>
          <%= link_to "Go somewhere", "/workoutmenus/new", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
      <img class="card-img-top" src="https://u.finc.com/cms/wp-content/uploads/2019/08/7c612c6d5b30b9f13a468015a385ec6d.jpg" alt="Card image cap" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">記録したトレーニングを確認する</h5>
          <p class="card-text">check my training</p>
          <%= link_to "Go somewhere", "/workoutmenus", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/workoutmenus/destroy.js.erb
$("td").html("<%= j(render @workoutmenus) %>")

app/views/workoutmenus/edit.html.erb
<div class="container-fuild">
  <h2>Training record Edit</h2>
  <hr>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= form_for @workoutmenu do |f| %>
          <div class="form-group col-md-12">
            <%= f.label :menu（メニュー） %>
            <%= f.collection_select :workoutdate_id, Workoutdate.all, :id, :menu, {}, class: 'form-control' %><br>
          </div>
          <div class="form-group col-md-12">
          <%= f.label :settype（セットタイプ） %><br>
            <div class="card-deck">
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :settype, "normalset" %>ノーマルセット</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :settype, "superset" %>スーパーセット</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :settype, "dropset" %>ドロップセット</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :settype, "giantset" %>ジャイアントセット</label>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= f.label :weight（重量）, class: "bmd-label-floating" %>
            <%= f.number_field :weight, class: 'form-control' %>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= f.label :reps（回数）, class: "bmd-label-floating" %>
            <%= f.number_field :reps, class: 'form-control' %>
          </div>
          <div class="form-group col-md-12">
            <br><%= f.submit "OK!!", class: "btn btn-raised btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/workoutmenus/index.html.erb
<div class="container-fuild">
  <div class="d-flex">
    <div class="mr-auto p-2"><h2>Training Record</h2></div>
    <div class="p-2">
      <%= form_tag(workoutmenus_path, :method => "get") do %>
        <%= date_field_tag :search, id: "sbox" %> 
        <%= submit_tag "🔍" ,:created_at => nil, class: "btn btn-raised btn-primary" %> 
      <% end %>
    </div>
  </div>
  <hr>
  <p>日付毎にトレーニング記録が管理されております。下記より日付を指定して確認してください。</p>
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="card-body">
          <h5>Todays TrainingList／本日実施のトレーニングメニュー</h5>
          <hr>
          <table class="table">
            <thead>
              <tr>
                <th>menu</th>
                <th>settype</th>
                <th>weight</th>
                <th>reps</th>
                <th></th>
              </tr>
            </thead>
          <%= render @workoutmenus %>
          </table>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
      <div class="card rounded-0 p-0 shadow-sm text-red text-center">
        <img class="card-img" src="https://assets.st-note.com/production/uploads/images/8596371/picture_pc_1e560f2a1716806a942a9a57eebdc00e.jpg" alt="Card image cap" style="height: 25rem;">
        <div class="card-img-overlay"><br><br><br><br>
          <h5 class="card-title">トレーニングを追加する</h5>
          <p class="card-text">本日もしっかりと記録していきましょう。</p>
          <%= link_to "トレーニングを追加する", "/workoutmenus/new", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/workoutmenus/new.html.erb
<div class="container-fuild">
  <h2>Training record</h2>
  <hr>
  <div class="form-group">
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Check !</h4>
      <p>実際に行ったメニューごとに登録をしていってください。</p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= form_for @workoutmenu do |f| %>
          <div class="form-group col-md-12">
            <%= f.label :menu（メニュー） %>
            <%= f.collection_select :workoutdate_id, Workoutdate.all, :id, :menu, {}, class: 'form-control' %><br>
          </div>
          <div class="form-group col-md-12">
          <%= f.label :settype（セットタイプ） %><br>
            <div class="card-deck">
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :settype, "normalset" %>ノーマルセット</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :settype, "superset" %>スーパーセット</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :settype, "dropset" %>ドロップセット</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :settype, "giantset" %>ジャイアントセット</label>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= f.label :weight（重量）, class: "bmd-label-floating" %>
            <%= f.number_field :weight, class: 'form-control' %>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= f.label :reps（回数）, class: "bmd-label-floating" %>
            <%= f.number_field :reps, class: 'form-control' %>
          </div>
          <div class="form-group col-md-12">
            <br><%= f.submit "OK!", class: "btn btn-raised btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
ーmemoー<br>
※セット数を追加するボタンを追加する<br>
※メニュー単位でカードを作成しているため、メニューを追加しカードも追加するボタンを作成する