config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :workoutmenus do
    collection do
      get 'confirm'
    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :useradvices, only: [:new, :create, :show]
  resources :advicediaries, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'confirm'
    end
    collection do
      get 'choice'
    end
    collection do
      get 'content'
    end
  end
  resources :fooddiaries do
    collection do
      get 'confirm'
    end
    # get :autocomplete_fooddate_foodname, :on => :collection
  end
  resources :idealweights
  resources :advicemenus do
    collection do
      get 'introduction'
    end
  end
  resources :weightchanges
end

app/models/advicediary.rb
class Advicediary < ApplicationRecord
  
  def self.search(search) 
    if search
      Advicediary.where(['created_at LIKE ?', "%#{search}%"])
    else
      Advicediary.where(created_at: Date.current.all_day)
    end
  end
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :advicemenu
  belongs_to :useradvice
  validates :useradvice_id, presence: true
  
  belongs_to :idealweight
  
end

app/controllers/advicediaries_controller.rb
class AdvicediariesController < ApplicationController
  
  def confirm
  end
  
  def index
    @advicediaries = current_user.advicediaries.search(params[:search])
    @advicemenus = Advicemenu.all
    @sum_column = current_user.advicediaries.size
    @advicemenu_a = Advicemenu.where(group: "A")
    @advicemenu_b = Advicemenu.where(group: "B")
    @advicemenu_c = Advicemenu.where(group: "C")
    @advicemenu_d = Advicemenu.where(group: "D")
    @advicemenu_e = Advicemenu.where(group: "E")
    @advicemenu_f = Advicemenu.where(group: "F")
    @advicemenu_g = Advicemenu.where(group: "G")
    @advicemenu_h = Advicemenu.where(group: "H")
    @advicemenu_i = Advicemenu.where(group: "I")
    @advicemenu_j = Advicemenu.where(group: "J")
    @advicemenu_k = Advicemenu.where(group: "K")
    @advicemenu_l = Advicemenu.where(group: "L")
    @advicemenu_m = Advicemenu.where(group: "M")
    @advicemenu_n = Advicemenu.where(group: "N")
    @advicemenu_o = Advicemenu.where(group: "O")
  end
  
  def choice
    @advicemenu_a = Advicemenu.where(group: "A")
    @advicemenu_b = Advicemenu.where(group: "B")
    @advicemenu_c = Advicemenu.where(group: "C")
    @advicemenu_d = Advicemenu.where(group: "D")
    @advicemenu_e = Advicemenu.where(group: "E")
    @advicemenu_f = Advicemenu.where(group: "F")
    @advicemenu_g = Advicemenu.where(group: "G")
    @advicemenu_h = Advicemenu.where(group: "H")
    @advicemenu_i = Advicemenu.where(group: "I")
    @advicemenu_j = Advicemenu.where(group: "J")
    @advicemenu_k = Advicemenu.where(group: "K")
    @advicemenu_l = Advicemenu.where(group: "L")
    @advicemenu_m = Advicemenu.where(group: "M")
    @advicemenu_n = Advicemenu.where(group: "N")
    @advicemenu_o = Advicemenu.where(group: "O")
  end
  
  def new
    @advicediary = current_user.advicediaries.new
    params[:group]
    @advicemenus = Advicemenu.where(group: params[:group])
  end
  
  def create
    @advicediary = current_user.advicediaries.create(weight: advicediary_params[:weight], reps: advicediary_params[:reps], advicemenu_id: advicediary_params[:advicemenu_id], user_id: current_user.id, useradvice_id: current_user.useradvice.id, idealweight_id: current_user.idealweight.id)
    redirect_to action: 'index'
  end
  
  def content
  end
  
  def destroy
    current_user.advicediaries.find(params[:id]).destroy
    @advicediaries = current_user.advicediaries.all
    redirect_to action: 'index'
  end
  
  def edit
    @advicediary = current_user.advicediaries.find(params[:id])
  end
  
  def update
    @advicediary = current_user.advicediaries.find(params[:id])
    @advicediary.update(advicediary_params)
    redirect_to action: 'index'
  end
  
  private
  def advicediary_params
    params.require(:advicediary).permit(:weight, :reps, :user_id, :menu, :advicemenu_id, :useradvice_id, :idealweight_id)
  end
  
end

app/helpers/advicediaries_helper.rb
module AdvicediariesHelper
end

app/views/advicediaries/_advicediary.html.erb
<tbody>
  <tr>
    <td><%= advicediary.advicemenu.menu %></td>
    <td><%= advicediary.weight %>kg</td>
    <td><%= advicediary.reps %>reps</td>
    <td>
      <div class="dropdown">
        <button class="btn bmd-btn-icon dropdown-toggle" type="button" id="ex1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="material-icons">more_vert</i>
        </button>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="ex1">
          <%= link_to "編集", edit_advicediary_path(advicediary), class: "dropdown-item" %>
          <%= link_to '削除', advicediary_path(advicediary), method: :delete, remote: true, class: "dropdown-item" %>
        </div>
      </div>
    </td>
  </tr>
</tbody>

app/views/advicediaries/choice.html.erb
<div class="container">
  <h4>選択するメニューを押下してください</h4>
  <hr>
  <p>あなたの目的にあったメニューになります。選択肢から本日行うメニューを選択してください。</p>
  <div class="form-group">
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Check !</h4>
      <p>提案されたメニューが複数ある場合は前回のトレーニングメニューと異なるメニューを選択するようにしてください。 </p>
    </div>
  </div>
  <% if current_user.useradvice.purpose == "ダイエット" && current_user.useradvice.frequency == 1 %>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
        <img class="card-img-top" src="https://myrevo.jp/fitness/wp-content/uploads/sites/4/2019/12/shutterstock_395138095.jpg" alt="" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">メニューA</h5>
          <p class="card-text">
            <% @advicemenu_a.each do |advicemenu| %>
            ■<%= advicemenu.menu %><br>
            <% end %>
          </p>
          <%= link_to "チョイスする", new_advicediary_path(group: "A"), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
  <% elsif current_user.useradvice.purpose == "ダイエット" && current_user.useradvice.frequency == 2 %>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
        <img class="card-img-top" src="https://myrevo.jp/fitness/wp-content/uploads/sites/4/2019/12/shutterstock_395138095.jpg" alt="" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">メニューA</h5>
          <p class="card-text">
            <% @advicemenu_b.each do |advicemenu| %>
            ■<%= advicemenu.menu %><br>
            <% end %>
          </p>
          <%= link_to "チョイスする", new_advicediary_path(group: "B"), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
        <img class="card-img-top" src="https://common-fitness.com/wp-content/uploads/2019/01/18/150512-460245.jpg" alt="" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">メニューB</h5>
          <p class="card-text">
            <% @advicemenu_c.each do |advicemenu| %>
            ■<%= advicemenu.menu %><br>
            <% end %>
          </p>
          <%= link_to "チョイスする", new_advicediary_path(group: "C"), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
  <% elsif current_user.useradvice.purpose == "ダイエット" && current_user.useradvice.frequency == 3 %>
    <h4><%= link_to "メニューA", new_advicediary_path(group: "D") %></h4>
    <% @advicemenu_d.each do |advicemenu| %>
      <%= advicemenu.menu %>
      <%= advicemenu.minimam_reps %>
      <%= advicemenu.max_reps %><br>
    <% end %>
    <h4><%= link_to "メニューB", new_advicediary_path(group: "E") %></h4>
    <% @advicemenu_e.each do |advicemenu| %>
      <%= advicemenu.menu %>
      <%= advicemenu.minimam_reps %>
      <%= advicemenu.max_reps %><br>
    <% end %>
    <h4><%= link_to "メニューC", new_advicediary_path(group: "F") %></h4>
    <% @advicemenu_f.each do |advicemenu| %>
      <%= advicemenu.menu %>
      <%= advicemenu.minimam_reps %>
      <%= advicemenu.max_reps %><br>
    <% end %>
  <% elsif current_user.useradvice.purpose == "ダイエット" && current_user.useradvice.frequency == 4 %>
    <h4><%= link_to "メニューA", new_advicediary_path(group: "G") %></h4>
    <% @advicemenu_g.each do |advicemenu| %>
      <%= advicemenu.menu %>
      <%= advicemenu.minimam_reps %>
      <%= advicemenu.max_reps %><br>
    <% end %>
    <h4><%= link_to "メニューB", new_advicediary_path(group: "H") %></h4>
    <% @advicemenu_h.each do |advicemenu| %>
      <%= advicemenu.menu %>
      <%= advicemenu.minimam_reps %>
      <%= advicemenu.max_reps %><br>
    <% end %>
    <h4><%= link_to "メニューC", new_advicediary_path(group: "I") %></h4>
    <% @advicemenu_i.each do |advicemenu| %>
      <%= advicemenu.menu %>
      <%= advicemenu.minimam_reps %>
      <%= advicemenu.max_reps %><br>
    <% end %>
    <h4><%= link_to "メニューD", new_advicediary_path(group: "J") %></h4>
    <% @advicemenu_j.each do |advicemenu| %>
      <%= advicemenu.menu %>
      <%= advicemenu.minimam_reps %>
      <%= advicemenu.max_reps %><br>
    <% end %>
  <% elsif current_user.useradvice.purpose == "ダイエット" && current_user.useradvice.frequency == 5 %>
  <div class="card-deck">
    <div class="card" style="width: 25rem;">
      <img class="card-img-top" src="https://smartlog-stat2.imgix.net/uploads/content/piece/2018/9/xyeasj/shutterstock_336330497-689x460.jpg?w=689&h=460&auto=compress&q=40" alt="Card image cap" style="height: 15rem;">
      <div class="card-body">
        <h5 class="card-title">メニューA</h5>
        <p class="card-text">
          <% @advicemenu_k.each do |advicemenu| %>
          ■<%= advicemenu.menu %><br>
          <% end %>
        </p>
        <%= link_to "Go somewhere", new_advicediary_path(group: "K"), class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="card" style="width: 25rem;">
      <img class="card-img-top" src="https://bodymaking.jp/wp-content/uploads/2017/05/hack-squat_00.png" alt="" style="height: 15rem;">
      <div class="card-body">
        <h5 class="card-title">メニューB</h5>
        <p class="card-text">
          <% @advicemenu_l.each do |advicemenu| %>
          ■<%= advicemenu.menu %><br>
          <% end %>
        </p>
        <%= link_to "Go somewhere", new_advicediary_path(group: "L"), class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="card" style="width: 25rem;">
      <img class="card-img-top" src="https://smartlog-stat2.imgix.net/uploads/content/piece/2019/4/tb7kc8/shutterstock_1188547474.jpg?w=689&h=459&auto=compress&q=35" alt="Card image cap" style="height: 15rem;">
      <div class="card-body">
        <h5 class="card-title">メニューC</h5>
        <p class="card-text">
          <% @advicemenu_m.each do |advicemenu| %>
          ■<%= advicemenu.menu %><br>
          <% end %>
        </p>
        <%= link_to "Go somewhere", new_advicediary_path(group: "M"), class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="card" style="width: 25rem;">
      <img class="card-img-top" src="https://mensdiet.net/wp-content/uploads/2018/07/db981c432e433b7566e6cc76f71fe5e2.gif" alt="Card image cap" style="height: 15rem;">
      <div class="card-body">
        <h5 class="card-title">メニューD</h5>
        <p class="card-text">
          <% @advicemenu_n.each do |advicemenu| %>
          ■<%= advicemenu.menu %><br>
          <% end %>
        </p>
        <%= link_to "Go somewhere", new_advicediary_path(group: "N"), class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="card" style="width: 25rem;">
      <img class="card-img-top" src="https://smartlog-stat2.imgix.net/uploads/content/piece/2019/7/4o0i49/shutterstock_609764243.jpg?w=689&h=459&auto=compress&q=35" alt="Card image cap" style="height: 15rem;">
      <div class="card-body">
        <h5 class="card-title">メニューE</h5>
        <p class="card-text">
          <% @advicemenu_o.each do |advicemenu| %>
          ■<%= advicemenu.menu %><br>
          <% end %>
        </p>
        <%= link_to "Go somewhere", new_advicediary_path(group: "O"), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/advicediaries/confirm.html.erb
<div class="container-fuild">
  <% if current_user.useradvice.present? %>
  <h2>Let's Training Today</h2>
  <hr>
  <p>Daily accumulation is the fastest way to success. Let's do our best today.</p>
  <p> Let's start!</p>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
        <img class="card-img-top" src="https://moneytimes.jp/files/topics/2827_ext_01_0.jpg" alt="Card image cap" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">本日のトレーニングを記録する</h5>
          <p class="card-text">今日も理想の身体に向けて頑張っていきましょう！</p>
          <%= link_to "Go somewhere", "/advicediaries/choice", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
        <img class="card-img-top" src="https://u.finc.com/cms/wp-content/uploads/2019/08/7c612c6d5b30b9f13a468015a385ec6d.jpg" alt="Card image cap" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">記録したトレーニングを確認する</h5>
          <p class="card-text">これまで記録したトレーニングを確認することもとても大切！</p>
          <%= link_to "Go somewhere", "/advicediaries", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% else %>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-md-offset-3">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Let's Bodymakesupport!</h4>
          <hr>
          <p class="card-text">本サービスでは『トレーニング』と『食事管理』の観点から理想の身体を作っていきます。
          <br>早速いくつかの質問に答えてスタートしていきましょう。</p>
          <%= link_to "入力する", "/useradvices/new", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/advicediaries/content.html.erb
<div class="container-fuild">
  <% if current_user.useradvice.present? %>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="card-header text-center"><br>
          <h3><%= current_user.username %>のボディメイク目標</h3><br>
          <p>入力いただいた情報からボディメイク目標を算出しました。
          <br>目標達成に向け地に足をつけ頑張っていきましょう</p>
        </div>
        <div class="card-body">
          <table class="table table-striped">
            <tr><th>BodymakePurpose／ボディメイク目的</th><th><%= current_user.useradvice.purpose %></th></tr>
            <tr><th>BodymakeFrequency／ボディメイク頻度</th><th>週<%= current_user.useradvice.frequency %>日</th></tr>
            <tr><td>Bodymake／ボディメイク期間</td><td><%= current_user.idealweight.period %>日</td></tr>
            <tr><th>Exerciselevel／運動量レベル</th><th><%= current_user.idealweight.exerciselevel %></th></tr>
            <tr><td>TargetWeight／目標体重</td><td><%= current_user.idealweight.targetweight %>kg</td></tr>
            <tr><td>Gap／乖離</td><td><%= current_user.idealweight.minusweight %>kg</td></tr>
          </table>
        </div>
        <%= link_to "back", advicediaries_path, class: 'btn btn-primary' %><br>
      </div>
    </div>
  </div>
  <% else %>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="card-header"><br>
          <h3><%= current_user.username %>の食事目標</h3><br>
        </div>
        <div class="card-body">
          <table class="table table-striped">
            <tr><td>Fooddiaryperiod／食事管理期間</td><td><%= current_user.idealweight.period %>日</td></tr>
            <tr><th>Exerciselevel／運動量レベル</th><th><%= current_user.idealweight.exerciselevel %></th></tr>
            <tr><td>TargetWeight／目標体重</td><td><%= current_user.idealweight.targetweight %>kg</td></tr>
            <tr><td>Gap／乖離</td><td><%= current_user.idealweight.minusweight %>kg</td></tr>
          </table>
        </div>
        <%= link_to "back", fooddiaries_path, class: 'btn btn-primary' %><br>
      </div>
    </div>
  </div>
  <% end %>
  
</div>

app/views/advicediaries/edit.html.erb
<div class="container">
  <div class="form-group">
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Check !</h4>
      <p>マシンの空き状況を見てメニューを選定するようにしてください。<br>
      下記のリンクに同じ意味合いのトレーニングをグループごとに分けているので参考にしながらトレーニングを行ってください<br>
      例えばベンチプレスであれば『バーベルベンチプレス』『ダンベルベンチプレス』『スミスマシンベンチプレス』などベンチプレスと言っても複数のマシンで同じ効果を得ることができます。</p>
      <%= link_to "Training-Group", "/advicemenus/introduction", class: 'btn btn-raised btn-primary' %>
    </div>
  </div>
  <br>
  <h2>Training Record Edit</h2>
  <hr><br>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= form_for @advicediary do |f| %>
          <div class="form-group col-md-12">
            <%= f.label :menu（メニュー） %>
            <%= f.collection_select :advicemenu_id, Advicemenu.all, :id, :menu, {}, class: 'form-control' %>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= f.label :weight（重量）, class: "bmd-label-floating" %>
            <%= f.number_field :weight, class: 'form-control' %>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= f.label :reps（回数）, class: "bmd-label-floating" %>
            <%= f.number_field :reps, class: 'form-control' %>
          </div>
          <div class="form-group col-md-12">
            <br><%= f.submit "送信", class: "btn btn-raised btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/advicediaries/index.html.erb
<div class="container-fuild">
  <% if current_user.useradvice.present? %>
  <div class="d-flex">
    <div class="mr-auto p-2"><h2>Training Record</h2></div>
    <div class="p-2">
      <%= form_tag(advicediaries_path, :method => "get") do %>
        <%= date_field_tag :search, id: "sbox" %> 
        <%= submit_tag "🔍" ,:created_at => nil, class: "btn btn-raised btn-primary" %>
      <% end %>
    </div>
  </div><hr>
  <div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">food_bank</i>
          </div>
          <p class="card-category text-right">Purpose／目的</p>
          <h5 class="card-title text-right"><%= current_user.useradvice.purpose %>
            <small class="card-text text-white"></small>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">event_note</i>
          </div>
          <p class="card-category text-right">BodymakePeriod／期間</p>
          <h5 class="card-title text-right"><%= current_user.idealweight.period %>
            <small class="card-text text-white">日</small>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">event_available</i>
          </div>
          <p class="card-category text-right">Frequency(week)／週あたりの頻度</p>
          <h5 class="card-title text-right">週<%= current_user.useradvice.frequency %>
            <small class="card-text text-white">日</small>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3 text-center">
        <img class="card-img" src="https://assets.st-note.com/production/uploads/images/8596371/picture_pc_1e560f2a1716806a942a9a57eebdc00e.jpg" alt="Card image cap" style="height: 10rem;">
        <div class="card-img-overlay"><br>
          <h5 class="card-title"><%= link_to "トレーニングを記録する", "/advicediaries/choice", class: "btn btn-raised btn-primary" %></h5>
        </div>
      </div>
    </div>
  </div><br>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="card-body">
          <h5>Todays TrainingList／本日実施のトレーニングメニュー</h5>
          <hr>
          <table class="table">
            <thead>
              <tr>
                <th>menu</th>
                <th>weight</th>
                <th>reps</th>
                <th></th>
              </tr>
            </thead>
          <%= render @advicediaries %>
          </table>
        </div>
      </div>
    </div>
  </div><br>
  <% else %>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-md-offset-3">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Let's Bodymakesupport!</h4>
          <hr>
          <p class="card-text">本サービスでは『トレーニング』と『食事管理』の観点から理想の身体を作っていきます。
          <br>早速いくつかの質問に答えてスタートしていきましょう。</p>
          <%= link_to "入力する", "/useradvices/new", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

  

app/views/advicediaries/new.html.erb
<div class="container">
  <h2>Suggested menu</h2>
  <hr>
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img class="card-img-top" src="https://qool.jp/wp-content/uploads/2020/04/shutterstock_388202932.png" alt="Card image cap" width="100%" height="200">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Todays menu</h5>
          <p class="card-text">
            <% @advicemenus.each do |advicemenu| %>
              ■<%= advicemenu.menu %>
              <%= advicemenu.minimam_reps %> ~
              <%= advicemenu.max_reps %>回
              <%= advicemenu.sets %>セット<br>
            <% end %>
          </p>
          <p class="card-text"><small class="text-muted">マシンの空き状況に応じて選定してください</small></p>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Check !</h4>
      <p>マシンの空き状況を見てメニューを選定するようにしてください。<br>
      下記のリンクに同じ意味合いのトレーニングをグループごとに分けているので参考にしながらトレーニングを行ってください<br>
      例えばベンチプレスであれば『バーベルベンチプレス』『ダンベルベンチプレス』『スミスマシンベンチプレス』などベンチプレスと言っても複数のマシンで同じ効果を得ることができます。</p>
      <%= link_to "Training-Group", "/advicemenus/introduction", class: 'btn btn-raised btn-primary' %>
    </div>
  </div>
  <br>
  <h2>Training record</h2>
  <hr><br>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= form_for @advicediary do |f| %>
          <div class="form-group col-md-12">
            <%= f.label :menu（メニュー） %>
            <%= f.collection_select :advicemenu_id, Advicemenu.all, :id, :menu, {}, class: 'form-control' %>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= f.label :weight（重量）, class: "bmd-label-floating" %>
            <%= f.number_field :weight, class: 'form-control' %>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= f.label :reps（回数）, class: "bmd-label-floating" %>
            <%= f.number_field :reps, class: 'form-control' %>
          </div>
          <div class="form-group col-md-12">
            <br><%= f.submit "送信", class: "btn btn-raised btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>