config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :workoutmenus do
    collection do
      get 'confirm'
    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :useradvices, only: [:new, :create, :show]
  resources :advicediaries, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'confirm'
    end
    collection do
      get 'choice'
    end
    collection do
      get 'content'
    end
  end
  resources :fooddiaries do
    collection do
      get 'confirm'
    end
    # get :autocomplete_fooddate_foodname, :on => :collection
  end
  resources :idealweights
  resources :advicemenus do
    collection do
      get 'introduction'
    end
  end
  resources :weightchanges
end

app/models/advicediary.rb
class Advicediary < ApplicationRecord
  
  def self.search(search) 
    if search
      Advicediary.where(['created_at LIKE ?', "%#{search}%"])
    else
      Advicediary.where(created_at: Date.current.all_day)
    end
  end
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :advicemenu
  belongs_to :useradvice
  validates :useradvice_id, presence: true
  
  belongs_to :idealweight
  
end

app/models/advicemenu.rb
class Advicemenu < ApplicationRecord
  has_many :advicediaries
  
  def self.search(search) 
    if search
      Advicemenu.where(['menu LIKE ?', "%#{search}%"])
    else
      Advicemenu.all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fooddate.rb
class Fooddate < ApplicationRecord
  has_many :fooddiaries
end

app/models/fooddiary.rb
class Fooddiary < ApplicationRecord
  
  # validates :gram, :kcal, :protein, :fat, :carbo, :timing, :fooddate_id, presence: true

  belongs_to :fooddate
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :idealweight
  
  def self.search(search) 
    if search
      Fooddiary.where(['created_at LIKE ?', "%#{search}%"]) 
    else
      Fooddiary.where(created_at: Date.current.all_day)
    end
  end

  before_save do
    self.kcal = (gram)*(fooddate.kcal)
    self.protein = (gram)*(fooddate.protein)
    self.fat = (gram)*(fooddate.fat)
    self.carbo = (gram)*(fooddate.carbo)
  end
  
  
end

app/models/idealweight.rb
class Idealweight < ApplicationRecord
  
  belongs_to :user
  has_many :fooddiaries
  has_many :advicediaries
  has_many :weightchanges
  
  before_save do
    if user.sex == "男"
      self.basemetabolism = 13.397*(weight)+4.799*(height)-5.677*(user.age)+88.362 #男性の場合
    else
      self.basemetabolism = 9.247*(weight)+3.098*(height)-4.33*(user.age)+447.593 #女性の場合
    end
    self.kcalburned = (basemetabolism)*(exerciselevel)
    self.minusweight = (weight)-(targetweight)
    self.minuskcal = (minusweight)*7000
    self.kcalintake = (kcalburned)-(minuskcal)/(period)
    self.intakeproteingram = (weight)*2
    self.intakeproteinkcal = (weight)*2*4
    self.intakefatgram = (weight)*0.7
    self.intakefatkcal = (weight)*0.7*9
    self.intakecarbokcal = (kcalintake)-(intakeproteinkcal)-(intakefatkcal)
    self.intakecarbogram = (intakecarbokcal)/4
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_one_attached :image
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :workoutmenus
  has_many :workoutdates
  has_many :fooddiaries
  has_one :useradvice
  has_many :advicediaries
  
  has_one :idealweight
  # accepts_nested_attributes_for :idealweight
  
  has_many :weightchanges
  
  def self.search(search) #index画面
    if search
      where(['created_at LIKE ?', "%#{search}%"]) 
    end
  end
  
  def set_date
    birthday.try(:strftime, "%Y%m%d").to_i
  end
  
  def today_date
    @today = Date.today
    @today.strftime("%Y%m%d").to_i
  end
  
  before_save do
    self.age = (today_date-set_date)/10000
  end
  
end

app/models/useradvice.rb
class Useradvice < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  
  has_many :advicediaries
end

app/models/weightchange.rb
class Weightchange < ApplicationRecord
  belongs_to :user
  belongs_to :idealweight
end

app/models/workoutdate.rb
class Workoutdate < ApplicationRecord
  has_many :workoutdiaries
  belongs_to :user
end

app/models/workoutmenu.rb
class Workoutmenu < ApplicationRecord
  
  validates :settype, :weight, :reps, presence: true
  
  def self.search(search) 
    if search
      Workoutmenu.where(['created_at LIKE ?', "%#{search}%"])
    else
      Workoutmenu.where(created_at: Date.current.all_day)
    end
  end
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :workoutdate
  
end

app/controllers/advicemenus_controller.rb
class AdvicemenusController < ApplicationController
  def introduction
    @advicemenus = Advicemenu.search(params[:search])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    # @workoutmenus = Workoutmenu.all
    @workoutmenus = params[:search].present? ? current_user.workoutmenus.where('created_at LIKE(?)', "%#{params[:search]}%"): []
  end
  
  def show
    @user = User.find(params[:id])
    @username = current_user.username
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end
  
  private
  def user_params
    params.require(:user).permit(:image, :username, :text, :sex, :area, :birthday, :age,
    idealweight_attributes: [:id, :height, :weight, :targetweight, :exerciselevel, :period, :basemetabolism, :kcalburned, :minusweight, :minuskcal, :kcalintake, :intakeproteingram, :intakeproteinkcal, :intakefatgram, :intakefatkcal, :intakecarbogram, :intakecarbokcal, :user_id])
  end
end

app/controllers/weightchanges_controller.rb
class WeightchangesController < ApplicationController
  
  def index
    @weightchanges = current_user.weightchanges.all.order("date DESC")
    @weightchange_today = current_user.weightchanges.find_by(date: Date.current.all_day)
    weightchanges = current_user.weightchanges.pluck(:date, :todayweight)
    @labels = weightchanges.map(&:first)
    @datas = weightchanges.map(&:second)
    @max = current_user.weightchanges.maximum(:todayweight)
    @minimum = current_user.weightchanges.minimum(:todayweight)
    @sum_column = current_user.weightchanges.size
  end
  
  def new
    @weightchange = Weightchange.new
  end
  
  def create
    @weightchange = Weightchange.create(date: weightchange_params[:date], todayweight: weightchange_params[:todayweight], user_id: current_user.id, idealweight_id: current_user.idealweight.id)
    redirect_to action: :index
  end
  
  def destroy
    current_user.weightchanges.find(params[:id]).destroy
    @weightchanges = current_user.weightchanges.all
    redirect_to action: 'index'
  end
  
  def edit
    @weightchange = current_user.weightchanges.find(params[:id])
  end
  
  def update
    @weightchange = current_user.weightchanges.find(params[:id])
    @weightchange.update(weightchange_params)
    redirect_to action: 'index'
  end
  
  private
  def weightchange_params
    params.require(:weightchange).permit(:date, :todayweight, :user_id, :idealweight_id)
  end
end

app/helpers/advicediaries_helper.rb
module AdvicediariesHelper
end

app/helpers/advicemenus_helper.rb
module AdvicemenusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fooddiaries_helper.rb
module FooddiariesHelper
end

app/helpers/idealweights_helper.rb
module IdealweightsHelper
end

app/helpers/useradvices_helper.rb
module UseradvicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weightchanges_helper.rb
module WeightchangesHelper
end

app/helpers/workoutmenus_helper.rb
module WorkoutmenusHelper
end

app/views/weightchanges/edit.html.erb
<div class="container-fuild">
  <div class="row">
    <div class="col-md-12">
      <h2>本日の体重を入力しよう</h2>
      <hr><br>
      <div class="card">
        <div class="card-body">
          <%= form_for @weightchange do |f| %>
            <%= f.label :date／本日の日付 %>
            <%= f.date_field :date, placeholder: "date", class: 'form-control' %><br>
            <%= f.label :todayweight／本日の体重 %>
            <%= f.number_field :todayweight, placeholder: "todayweight", step: "0.1", class: 'form-control' %><br>
            <%= f.submit "送信", class: "btn btn-raised btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/weightchanges/index.html.erb
<div class="container-fuild">
  <h2><%= current_user.username %>の体重管理</h2>
  <hr>
  <div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">today</i>
          </div>
          <p class="card-category text-right">TodayWeight／本日の体重</p>
          <% if @weightchange_today.present? %>
          <h5 class="card-title text-right"><%= @weightchange_today.todayweight %>
            <small class="card-text text-white">KG</small>
          </h5>
          <% else %>
            <h5 class="card-title text-right"><%= link_to "本日の体重を記録する", new_weightchange_path, class: "btn btn-danger" %></h5>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">date_range</i>
          </div>
          <p class="card-category text-right">TargetWeight／目標体重</p>
          <h5 class="card-title text-right"><%= current_user.idealweight.targetweight %>
            <small class="card-text text-white">KG</small>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">event</i>
          </div>
          <p class="card-category text-right">BodymakePeriod／ボディメイク期間</p>
          <h5 class="card-title text-right"><%= @sum_column %>日目／<%= current_user.idealweight.period %>
            <small class="card-text text-white">日</small>
          </h5>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-secondary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">create</i>
          </div>
          <p class="card-category text-right">WeightRecord／本日の体重を記録する</p>
          <h5 class="card-title text-right"><%= link_to "本日の体重を記録する", new_weightchange_path, class: "btn btn-primary" %></h5>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="form-group col-md-12"><br>
          <h5>WeightDiaryRecord／体重記録</h5>
          <hr>
          <div class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <th>Date／日付</th>
                  <th>Weight／体重</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @weightchanges.each do |weightchange| %>
                <tr><td><%= weightchange.date %></td>
                <td><%= weightchange.todayweight %>Kg</td>
                <td><%= link_to "編集", edit_weightchange_path(weightchange), class: "" %></td>
                <td><%= link_to '削除', weightchange_path(weightchange), method: :delete, remote: true, class: "" %></td></tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div><br>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="form-group col-md-12"><br>
          <h5>WeightChange／期間中体重推移</h5>
          <hr>
          <% if @weightchanges.present? %>
          <canvas id="myLineChart"></canvas>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
          <script>
          var ctx = document.getElementById("myLineChart");
          var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: <%= @labels.to_json.html_safe %>,
              // labels: ["0701", "0702", "0703", "0704", "0705", "0706", "0707"],
              datasets: [
                {
                  label: '実績推移',
                  data: <%= @datas %>,
                  borderColor: "rgba(255,0,0,1)",
                  backgroundColor: "rgba(0,0,0,0)"
                },
                // {
                //   label: '期待値',
                //   data: [65, 64, 63, 62, 61, 60, 59, 58],
                //   borderColor: "rgba(0,0,255,1)",
                //   backgroundColor: "rgba(0,0,0,0)"
                // }
              ],
            },
            options: {
              title: {
                display: true,
                text: '体重推移（○月☓日~○月☓日）'
              },
              scales: {
                yAxes: [{
                  ticks: {
                    suggestedMax: <%= @max %> +5,
                    suggestedMin: <%= @minimum %> -5,
                    stepSize: 1,
                    callback: function(value, index, values){
                      return  value +  'KG'
                    }
                  }
                }]
              },
            }
          });
          </script>
          <% else %>
          <p>Nodate...</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/weightchanges/new.html.erb
<div class="container-fuild">
  <div class="row">
    <div class="col-md-12">
      <h2>本日の体重を入力しよう</h2>
      <hr><br>
      <div class="card">
        <div class="card-body">
          <%= form_for @weightchange do |f| %>
            <%= f.label :date／本日の日付 %>
            <%= f.date_field :date, placeholder: "date", class: 'form-control' %><br>
            <%= f.label :todayweight／本日の体重 %>
            <%= f.number_field :todayweight, placeholder: "todayweight", step: "0.1", class: 'form-control' %><br>
            <%= f.submit "送信", class: "btn btn-raised btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>