config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :workoutmenus do
    collection do
      get 'confirm'
    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :useradvices, only: [:new, :create, :show]
  resources :advicediaries, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'confirm'
    end
    collection do
      get 'choice'
    end
    collection do
      get 'content'
    end
  end
  resources :fooddiaries do
    collection do
      get 'confirm'
    end
    # get :autocomplete_fooddate_foodname, :on => :collection
  end
  resources :idealweights
  resources :advicemenus do
    collection do
      get 'introduction'
    end
  end
  resources :weightchanges
end

app/models/advicediary.rb
class Advicediary < ApplicationRecord
  
  def self.search(search) 
    if search
      Advicediary.where(['created_at LIKE ?', "%#{search}%"])
    else
      Advicediary.where(created_at: Date.current.all_day)
    end
  end
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :advicemenu
  belongs_to :useradvice
  validates :useradvice_id, presence: true
  
  belongs_to :idealweight
  
end

app/models/advicemenu.rb
class Advicemenu < ApplicationRecord
  has_many :advicediaries
  
  def self.search(search) 
    if search
      Advicemenu.where(['menu LIKE ?', "%#{search}%"])
    else
      Advicemenu.all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fooddate.rb
class Fooddate < ApplicationRecord
  has_many :fooddiaries
end

app/models/fooddiary.rb
class Fooddiary < ApplicationRecord
  
  # validates :gram, :kcal, :protein, :fat, :carbo, :timing, :fooddate_id, presence: true

  belongs_to :fooddate
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :idealweight
  
  def self.search(search) 
    if search
      Fooddiary.where(['created_at LIKE ?', "%#{search}%"]) 
    else
      Fooddiary.where(created_at: Date.current.all_day)
    end
  end

  before_save do
    self.kcal = (gram)*(fooddate.kcal)
    self.protein = (gram)*(fooddate.protein)
    self.fat = (gram)*(fooddate.fat)
    self.carbo = (gram)*(fooddate.carbo)
  end
  
  
end

app/models/idealweight.rb
class Idealweight < ApplicationRecord
  
  belongs_to :user
  has_many :fooddiaries
  has_many :advicediaries
  has_many :weightchanges
  
  before_save do
    if user.sex == "男"
      self.basemetabolism = 13.397*(weight)+4.799*(height)-5.677*(user.age)+88.362 #男性の場合
    else
      self.basemetabolism = 9.247*(weight)+3.098*(height)-4.33*(user.age)+447.593 #女性の場合
    end
    self.kcalburned = (basemetabolism)*(exerciselevel)
    self.minusweight = (weight)-(targetweight)
    self.minuskcal = (minusweight)*7000
    self.kcalintake = (kcalburned)-(minuskcal)/(period)
    self.intakeproteingram = (weight)*2
    self.intakeproteinkcal = (weight)*2*4
    self.intakefatgram = (weight)*0.7
    self.intakefatkcal = (weight)*0.7*9
    self.intakecarbokcal = (kcalintake)-(intakeproteinkcal)-(intakefatkcal)
    self.intakecarbogram = (intakecarbokcal)/4
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_one_attached :image
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :workoutmenus
  has_many :workoutdates
  has_many :fooddiaries
  has_one :useradvice
  has_many :advicediaries
  
  has_one :idealweight
  # accepts_nested_attributes_for :idealweight
  
  has_many :weightchanges
  
  def self.search(search) #index画面
    if search
      where(['created_at LIKE ?', "%#{search}%"]) 
    end
  end
  
  def set_date
    birthday.try(:strftime, "%Y%m%d").to_i
  end
  
  def today_date
    @today = Date.today
    @today.strftime("%Y%m%d").to_i
  end
  
  before_save do
    self.age = (today_date-set_date)/10000
  end
  
end

app/models/useradvice.rb
class Useradvice < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  
  has_many :advicediaries
end

app/models/weightchange.rb
class Weightchange < ApplicationRecord
  belongs_to :user
  belongs_to :idealweight
end

app/models/workoutdate.rb
class Workoutdate < ApplicationRecord
  has_many :workoutdiaries
  belongs_to :user
end

app/models/workoutmenu.rb
class Workoutmenu < ApplicationRecord
  
  validates :settype, :weight, :reps, presence: true
  
  def self.search(search) 
    if search
      Workoutmenu.where(['created_at LIKE ?', "%#{search}%"])
    else
      Workoutmenu.where(created_at: Date.current.all_day)
    end
  end
  
  belongs_to :user
  validates :user_id, presence: true
  
  belongs_to :workoutdate
  
end

app/controllers/advicemenus_controller.rb
class AdvicemenusController < ApplicationController
  def introduction
    @advicemenus = Advicemenu.search(params[:search])
  end
end

app/controllers/fooddiaries_controller.rb
class FooddiariesController < ApplicationController
  # protect_from_forgery with: :exception
  autocomplete :fooddate, :foodname, :full => true # 追加
  
  def index
    @fooddiary_morning = current_user.fooddiaries.search(params[:search]).where(timing: '朝食')
    @fooddiary_lunch = current_user.fooddiaries.search(params[:search]).where(timing: '昼食')
    @fooddiary_dinner = current_user.fooddiaries.search(params[:search]).where(timing: '夕食')
    @fooddiary_snack = current_user.fooddiaries.search(params[:search]).where(timing: '間食')
    @fooddiaries = current_user.fooddiaries.search(params[:search])
    @fooddiary_sum_kcal = @fooddiaries.sum { |fooddiary| fooddiary[:kcal] }
    @fooddiary_sum_protein = @fooddiaries.sum { |fooddiary| fooddiary[:protein] }
    @fooddiary_sum_fat = @fooddiaries.sum { |fooddiary| fooddiary[:fat] }
    @fooddiary_sum_carbo = @fooddiaries.sum { |fooddiary| fooddiary[:carbo] }
  end
  
  def new
    @fooddiary = current_user.fooddiaries.new
    if params[:fooddate] && params[:fooddate][:foodname]
    fooddate_foodname = params[:fooddate][:foodname]
    @fooddates = Fooddate.where(foodname: fooddate_foodname)
    else
    @fooddates = Fooddate.all
    end
  end
  
  def create
    @fooddiary = Fooddiary.create(gram: fooddiary_params[:gram], kcal: fooddiary_params[:kcal], protein: fooddiary_params[:protein], fat: fooddiary_params[:fat], 
                  carbo: fooddiary_params[:carbo], timing: fooddiary_params[:timing], fooddate_id: fooddiary_params[:fooddate_id], user_id: current_user.id, idealweight_id: current_user.idealweight.id )
    redirect_to action: 'index'
  end
  
  def destroy
    current_user.fooddiaries.find(params[:id]).destroy
    @fooddiaries = current_user.fooddiaries.all
    redirect_to action: 'index'
  end
  
  def edit
    @fooddiary = current_user.fooddiaries.find(params[:id])
  end
  
  def update
    @fooddiary = current_user.fooddiaries.find(params[:id])
    @fooddiary.update(fooddiary_params)
    redirect_to action: 'index'
  end
  
  private
  def fooddiary_params
    params.require(:fooddiary).permit(:gram, :kcal, :protein, :fat, :carbo, :timing, :fooddate_id, :user_id, :idealweight_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    # @workoutmenus = Workoutmenu.all
    @workoutmenus = params[:search].present? ? current_user.workoutmenus.where('created_at LIKE(?)', "%#{params[:search]}%"): []
  end
  
  def show
    @user = User.find(params[:id])
    @username = current_user.username
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end
  
  private
  def user_params
    params.require(:user).permit(:image, :username, :text, :sex, :area, :birthday, :age,
    idealweight_attributes: [:id, :height, :weight, :targetweight, :exerciselevel, :period, :basemetabolism, :kcalburned, :minusweight, :minuskcal, :kcalintake, :intakeproteingram, :intakeproteinkcal, :intakefatgram, :intakefatkcal, :intakecarbogram, :intakecarbokcal, :user_id])
  end
end

app/helpers/advicediaries_helper.rb
module AdvicediariesHelper
end

app/helpers/advicemenus_helper.rb
module AdvicemenusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fooddiaries_helper.rb
module FooddiariesHelper
end

app/helpers/idealweights_helper.rb
module IdealweightsHelper
end

app/helpers/useradvices_helper.rb
module UseradvicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weightchanges_helper.rb
module WeightchangesHelper
end

app/helpers/workoutmenus_helper.rb
module WorkoutmenusHelper
end

app/views/fooddiaries/_fooddiary.html.erb
<tbody>
  <tr>
    <td></td>
    <td><%= fooddiary.fooddate.foodname %></td>
    <td><%= fooddiary.gram %>g</td>
    <td><%= fooddiary.kcal %>kcal</td>
    <td><%= fooddiary.protein %>g</td>
    <td><%= fooddiary.fat %>g</td>
    <td><%= fooddiary.carbo %>g</td>
    <td>
      <div class="dropdown">
        <button class="btn bmd-btn-icon dropdown-toggle" type="button" id="ex1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="material-icons">more_vert</i>
        </button>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="ex1">
          <%= link_to "編集", edit_fooddiary_path(fooddiary), class: "dropdown-item" %>
          <%= link_to '削除', fooddiary_path(fooddiary), method: :delete, remote: true, class: "dropdown-item" %>
        </div>
      </div>
    </td>
  </tr>
</tbody>

app/views/fooddiaries/confirm.html.erb
<div class="container-fuild">
  <% if current_user.idealweight.present? %>
  <h2>Food Diary</h2>
  <hr>
  <p>Food is the most important thing for bodymake. If you can't manage yourself, you can't succeed.</p>
  <p> Let's start!</p>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
        <img class="card-img-top" src="https://dol.ismcdn.jp/mwimgs/1/f/670m/img_1f2ee769c22f051eec72d1039c359b4c1241626.jpg" alt="Card image cap" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">本日の食事内容を記録する</h5>
          <p class="card-text">ボディメイクにおいて食事はとても大切です。しっかりと記録しましょう。</p>
          <%= link_to "Go somewhere", "/fooddiaries/new", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
      <img class="card-img-top" src="https://wglint.com/wp-content/uploads/2017/01/pie-chart-1569175_960_720-300x246.jpg" alt="Card image cap" style="height: 30rem;">
        <div class="card-body">
          <h5 class="card-title">食事内容を確認する</h5>
          <p class="card-text">これまで記録した食事内容を確認することもとても大切！</p>
          <%= link_to "Go somewhere", "/fooddiaries", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% else %>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-md-offset-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">食事管理に必要な情報を入力しよう</h5>
          <p class="card-text">情報を入力することで1日あたりの必要なPFCを知ることができます</p>
          <%= link_to "Go somewhere", "/idealweights/new", class: "btn btn-raised btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/fooddiaries/edit.html.erb
<div class="container">
  <h2>Let's Foodrecord</h2>
  <hr>
  <p>Please enter the food you actually ate.</p>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= form_for @fooddiary do |f| %>
            <%= f.label :Foodmenu／食品名 %>
            <div class="form-group">
            <%= f.collection_select :fooddate_id, Fooddate.all, :id, :foodname, {}, class: 'form-control' %><br><br>
            </div>
            <%= f.label :gram／グラム %>
            <%= f.number_field :gram, placeholder: "gram", class: 'form-control' %><br>
            <%= f.label :timing／タイミング %>
            <div class="card-deck">
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :timing, "朝食" %>朝食</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :timing, "昼食" %>昼食</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :timing, "夕食" %>夕食</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :timing, "間食" %>間食</label>
                  </div>
                </div>
              </div>
            </div>
              <%= f.submit "送信", class: "btn btn-raised btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
※追加ボタンを作成しブロックを増やせるようにし一度で全ての記入を可能としたい

app/views/fooddiaries/index.html.erb
<div class="container-fuild">
  <div class="d-flex">
    <div class="mr-auto p-2"><h2>Food Record</h2></div>
    <div class="p-2">
      <%= form_tag(fooddiaries_path, :method => "get") do %>
        <%= date_field_tag :search, id: "sbox" %> 
        <%= submit_tag "🔍" ,:created_at => nil, class: "btn btn-raised btn-primary" %> 
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">food_bank</i>
          </div>
          <p class="card-category text-right">Kcal／カロリー</p>
          <h5 class="card-title text-right"><%= @fooddiary_sum_kcal %>／<%= current_user.idealweight.kcalintake %>
            <small class="card-text text-white">KCAL</small>
          </h5>
          <p class="card-text text-right">残り：<%= current_user.idealweight.kcalintake - @fooddiary_sum_kcal %>kcal</p>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">android</i>
          </div>
          <p class="card-category text-right">Protein／タンパク質</p>
          <h5 class="card-title text-right"><%= @fooddiary_sum_protein %>／<%= current_user.idealweight.intakeproteingram %>
            <small class="card-text text-white">G</small>
          </h5>
          <p class="card-text text-right">残り：<%= current_user.idealweight.intakeproteingram - @fooddiary_sum_protein %>g</p>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">local_pizza</i>
          </div>
          <p class="card-category text-right">Fat／脂質</p>
          <h5 class="card-title text-right"><%= @fooddiary_sum_fat %>／<%= current_user.idealweight.intakefatgram %>
            <small class="card-text text-white">G</small>
          </h5>
          <p class="card-text text-right">残り：<%= current_user.idealweight.intakefatgram - @fooddiary_sum_fat %>g</p>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats text-white bg-primary mb-3">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">rice_bowl</i>
          </div>
          <p class="card-category text-right">Carbo／炭水化物</p>
          <h5 class="card-title text-right"><%= @fooddiary_sum_carbo %>／<%= current_user.idealweight.intakecarbogram %>
            <small class="card-text text-white">G</small>
          </h5>
          <p class="card-text text-right">残り：<%= current_user.idealweight.intakecarbogram - @fooddiary_sum_carbo %>g</p>
        </div>
      </div>
    </div>
  </div><br>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="form-group col-md-12"><br>
        <h5>Foodlist／食事一覧</h5>
        <hr>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Morning／朝食</th>
                <th>foodname</th>
                <th>gram</th>
                <th>kcal</th>
                <th>protein</th>
                <th>fat</th>
                <th>carbo</th>
                <th></th>
              </tr>
            </thead>
            <%= render @fooddiary_morning %>
            <thead>
              <tr>
                <th>Lunch／昼食</th>
                <th></th><th></th><th></th><th></th><th></th><th></th><th></th>
              </tr>
            </thead>  
            <%= render @fooddiary_lunch %>
            <thead>
              <tr>
                <th>Dinner／夕食</th>
                <th></th><th></th><th></th><th></th><th></th><th></th><th></th>
              </tr>
            </thead>
            <%= render @fooddiary_dinner %>
            <thead>
              <tr>
                <th>Snack／間食</th>
                <th></th><th></th><th></th><th></th><th></th><th></th><th></th>
              </tr>
            </thead>
            <%= render @fooddiary_snack %>
          </table>
        </div>
      </div>
    </div>
  </div><br>
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="form-group col-md-12"><br>
          <h5>Important／数値見える化</h5>
          <hr>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Total／合計</th>
              <th>kcal</th>
              <th>protein</th>
              <th>fat</th>
              <th>carbo</th>
            </tr>
          </thead>
          <tbody>
            <td></td>
            <td><%= @fooddiary_sum_kcal %>kcal</td>
            <td><%= @fooddiary_sum_protein %>g</td>
            <td><%= @fooddiary_sum_fat %>g</td>
            <td><%= @fooddiary_sum_carbo %>g</td>
          </tbody>
          <thead>
            <tr>
            <th>Target／目標</th>  
            <th></th><th></th><th></th><th></th>
          </thead>
          <tbody>
            <td></td>
            <td><%= current_user.idealweight.kcalintake %>kcal</td>
            <td><%= current_user.idealweight.intakeproteingram %>g</td>
            <td><%= current_user.idealweight.intakefatgram %>g</td>
            <td><%= current_user.idealweight.intakecarbogram %>g</td>
          </tbody>
          <thead>
            <tr>
              <th>Remaining／残り</th>
              <th></th><th></th><th></th><th></th>
            </tr><br>
          </thead>
          <tbody>
            <td></td>
            <td><%= current_user.idealweight.kcalintake - @fooddiary_sum_kcal %>kcal</td>
            <td><%= current_user.idealweight.intakeproteingram - @fooddiary_sum_protein %>g</td>
            <td><%= current_user.idealweight.intakefatgram - @fooddiary_sum_fat %>g</td>
            <td><%= current_user.idealweight.intakecarbogram - @fooddiary_sum_carbo %>g</td>
          </tbody>
        </table>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
      <div class="card rounded-0 p-0 shadow-sm text-black text-center">
        <img class="card-img" src="https://cdn.asagei.com/syokuraku/uploads/2019/07/20190711-kinnikumesi01.jpg" alt="Card image cap" style="height: 25rem;">
        <div class="card-img-overlay"><br><br><br><br>
          <h5 class="card-title">食事を追加する</h5>
          <p class="card-text">本日も丁寧に記録していきましょう。</p>
          <%= link_to "食事を追加する", "/fooddiaries/new", class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div><br>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="form-group col-md-12"><br>
          <h5>Progress／進捗</h5>
          <hr><br>
          <th>Kcal／カロリー</th>
          <div class="pull-right"><%= @fooddiary_sum_kcal %>kcal／<%= current_user.idealweight.kcalintake %>kcal</div>
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: <%= @fooddiary_sum_kcal*100 / current_user.idealweight.kcalintake %>%;" aria-valuemin="0" aria-valuemax="100">
            </div>
          </div>
          <th>Protein／タンパク質</th>
          <div class="pull-right"><%= @fooddiary_sum_protein %>g／<%= current_user.idealweight.intakeproteingram %>g</div>
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: <%= @fooddiary_sum_protein*100 / current_user.idealweight.intakeproteingram %>%;" aria-valuemin="0" aria-valuemax="100">
            </div>
          </div>
          <th>Fat／脂質</th>
          <div class="pull-right"><%= @fooddiary_sum_fat %>g／<%= current_user.idealweight.intakefatgram %>g</div>
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: <%= @fooddiary_sum_fat*100 / current_user.idealweight.intakefatgram %>%;" aria-valuemin="0" aria-valuemax="100">
            </div>
          </div>
          <th>Carbo／炭水化物</th>
          <div class="pull-right"><%= @fooddiary_sum_carbo %>g／<%= current_user.idealweight.intakecarbogram %>g</div>
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: <%= @fooddiary_sum_carbo*100 / current_user.idealweight.intakecarbogram %>%;" aria-valuemin="0" aria-valuemax="100">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card rounded-0 p-0 shadow-sm">
        <div class="form-group col-md-12"><br>
          <h5>Target PFC／目標PFCバランス</h5>
          <hr>
            <canvas id="myPieChart"></canvas>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
            <script>
            var ctx = document.getElementById("myPieChart");
            var myPieChart = new Chart(ctx, {
              type: 'pie',
              data: {
                labels: ["Protein", "Fat", "Carbo"],
                datasets: [{
                    backgroundColor: [
                        "#BB5179",
                        "#FAFF67",
                        "#3C00FF"
                    ],
                    data: [<%= current_user.idealweight.intakeproteingram %>, 
                    <%= current_user.idealweight.intakefatgram %>,
                    <%= current_user.idealweight.intakecarbogram %>]
                }]
              },
              options: {
                title: {
                  // display: true,
                  // text: '血液型 割合'
                }
              }
            });
            </script>
        </div>
      </div>
    </div>
  </div><br>
  
  

app/views/fooddiaries/new.html.erb
<div class="container">
  <h2>Let's Foodrecord</h2>
  <hr>
  <p>Please enter the food you actually ate.</p>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card">
        <div class="card-body">
          <%= form_for @fooddiary do |f| %>
            <%= f.label :Foodmenu／食品名 %>
            <div class="form-group">
            <%= f.collection_select :fooddate_id, Fooddate.all, :id, :foodname, {}, class: 'form-control' %><br><br>
            </div>
            <%= f.label :gram／グラム %>
            <%= f.number_field :gram, placeholder: "gram", class: 'form-control' %><br>
            <%= f.label :timing／タイミング %>
            <div class="card-deck">
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :timing, "朝食" %>朝食</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :timing, "昼食" %>昼食</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :timing, "夕食" %>夕食</label>
                  </div>
                </div>
              </div>
              <div class="card bg-light mb-3" style="max-width: 20rem;">
                <div class="card-header">
                  <div class="radio">
                    <label><%= f.radio_button :timing, "間食" %>間食</label>
                  </div>
                </div>
              </div>
            </div>
              <%= f.submit "送信", class: "btn btn-raised btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
※追加ボタンを作成しブロックを増やせるようにし一度で全ての記入を可能としたい